title: O.R.I. Containment District - Outpost-60
description: suffering
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Primary Operations.: https://www.roblox.com/groups/7595770/Orion-Research-Initiative#!/about
  Containment District.: https://www.roblox.com/groups/8664655/Energy-Corp-Response-Team#!/about
  Administrative Operations.: https://www.roblox.com/groups/9777413/The-Foundation-SCP-F#!/about
  
aux_links_new_tab: true

callouts:
  warning:
    title: Warning
    color: red
  new:
    title: New
    color: green
  old:
    title: Old/Not Updated
    color: yellow
  important:
    title: IMPORTANT
    color: blue

color_scheme: dark
